[versions]
flyway = "13.1.0"
jackson3 = "3.2.2"
testcontainers = "2.0.5"
ibmMq = "10.0.0.0"
jaxb = "4.0.9"
sasGradlePlugins = "20260807.0944"
tbd-libs = "20260811.1310"

[libraries]
cloud-sql-postgres-socket-factory = "com.google.cloud.sql:postgres-socket-factory:1.29.0"
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hikaricp = "com.zaxxer:HikariCP:7.1.0"
ibm-mq-allclient = { module = "com.ibm.mq:com.ibm.mq.allclient", version.ref = "ibmMq" }
jackson-dataformat-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jackson3-bom = { module = "tools.jackson:jackson-bom", version.ref = "jackson3" }
jakarta-xml-bind-api = "jakarta.xml.bind:jakarta.xml.bind-api:4.0.5"
jaxb-runtime = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "jaxb" }
kotliquery = "com.github.seratch:kotliquery:1.9.1"
ktor-server-auth = { module = "io.ktor:ktor-server-auth" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }
ktor-server-double-receive = { module = "io.ktor:ktor-server-double-receive" }
logback-classic = "ch.qos.logback:logback-classic:1.6.1"
logback-logstash-encoder = "net.logstash.logback:logstash-logback-encoder:9.0"
postgresql = "org.postgresql:postgresql:42.7.13"
rapids-and-rivers = "com.github.navikt:rapids-and-rivers:2026042008201776666058"
tbd-libs-azure = { module = "com.github.navikt.tbd-libs:azure-token-client-default", version.ref = "tbd-libs" }
tbd-libs-naisful-app = { module = "com.github.navikt.tbd-libs:naisful-app", version.ref = "tbd-libs" }
tbd-libs-retry = { module = "com.github.navikt.tbd-libs:retry", version.ref = "tbd-libs" }
tbdLibs-resultObject = { module = "com.github.navikt.tbd-libs:result-object", version.ref = "tbd-libs" }

apache-artemis = "org.apache.activemq:apache-artemis:2.55.0"
httpclient5-fluent = "org.apache.httpcomponents.client5:httpclient5-fluent:5.6.4"
ktor-client-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation" }
mock-oauth2-server = "no.nav.security:mock-oauth2-server:6.0.2"
mockk = "io.mockk:mockk:1.14.11"
sykepengerLibs-testing = "no.nav.sykepenger.libs:testing:20260829.1737"
tbd-libs-mock-http-client = { module = "com.github.navikt.tbd-libs:mock-http-client", version.ref = "tbd-libs" }
tbd-libs-naisful-test-app = { module = "com.github.navikt.tbd-libs:naisful-test-app", version.ref = "tbd-libs" }
tbd-libs-postgres-testdatabaser = { module = "com.github.navikt.tbd-libs:postgres-testdatabaser", version.ref = "tbd-libs" }
tbd-libs-rapids-and-rivers-test = { module = "com.github.navikt.tbd-libs:rapids-and-rivers-test", version.ref = "tbd-libs" }
wiremock = "org.wiremock:wiremock-jetty12:3.13.2"

[bundles]
logback = [
    "logback-classic",
    "logback-logstash-encoder",
]

[plugins]
sas-deployable = { id = "no.nav.helse.sas.sas-deployable", version.ref = "sasGradlePlugins" }
sas-root = { id = "no.nav.helse.sas.sas-root", version.ref = "sasGradlePlugins" }
