apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: tbd
  name: spenn-mq
  namespace: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  kafka:
    pool: nav-dev
  accessPolicy:
    outbound:
      external:
        - host: b27apvl220.preprod.local
          ports:
            - port: 1413
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  envFrom:
    - secret: spenn
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spenn-mq-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: MQ_HOSTNAME
      value: b27apvl220.preprod.local
    - name: MQ_CHANNEL
      value: Q1_SPENN
    - name: MQ_PORT
      value: "1413"
    - name: MQ_QUEUE_MANAGER
      value: MQLS02
    - name: OPPDRAG_QUEUE_SEND
      value: QA.Q1_231.OB04_OPPDRAG_XML
    - name: OPPDRAG_QUEUE_MOTTAK
      value: QA.Q1_SPENN.OPPDRAG_SP_XML_KVITT
    - name: MQ_OPPDRAG_AUTHENTICATION
      value: "true"
