apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
    db: spenn
  name: spenn-avstemming
  namespace: tbd
spec:
  image: {{image}}
  schedule: "0 7 * * *"
  kafka:
    pool: nav-dev
  ttlSecondsAfterFinished: 43200
  backoffLimit: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 4096Mi
      cpu: 2000m
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/cloudsql.client
  envFrom:
    - secret: google-sql-spenn-spenn-spenn-avstemming-bc3e42cd
    - secret: spenn
  accessPolicy:
    outbound:
      rules:
        - application: prometheus
          namespace: nais
  env:
  - name: CRON_JOB_MODE
    value: "true"
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: DATABASE_REGION
    value: "europe-north1"
  - name: DATABASE_INSTANCE
    value: "spenn"
  - name: MQ_HOSTNAME
    value: b27apvl220.preprod.local
  - name: MQ_CHANNEL
    value: Q1_SPENN
  - name: MQ_PORT
    value: "1413"
  - name: MQ_QUEUE_MANAGER
    value: MQLS02
  - name: MQ_OPPDRAG_AUTHENTICATION
    value: "true"
  - name: AVSTEMMING_QUEUE_SEND
    # Setter target client = 1 for bakoverkompabilitet med stormaskin
    value: queue:///QA.Q1_234.OB29_AVSTEMMING_XML?targetClient=1