apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: tbd
  name: spenn-avstemming-cronjob
  namespace: tbd
spec:
  image: {{image}}
  schedule: "0 7 * * *"
  kafka:
    pool: nav-dev
  ttlSecondsAfterFinished: 43200
  backoffLimit: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 4096Mi
      cpu: 2000m
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1