apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: tbd
    db: spenn
  name: spenn-opprydding-dev
  namespace: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/cloudsql.client
  envFrom:
    - secret: google-sql-spenn-spenn-spenn-opprydding-38bed636
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spenn-opprydding-dev-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: DATABASE_REGION
      value: "europe-north1"
    - name: DATABASE_INSTANCE
      value: "spenn"