apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: tbd
  name: spenn-simulering
  namespace: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: RollingUpdate
  liveness:
    initialDelay: 5
    path: /isalive
  readiness:
    initialDelay: 5
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    cpuThresholdPercentage: 75
    max: 2
    min: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  vault:
    enabled: false
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  envFrom:
    - secret: spenn
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spenn-simulering-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: SIMULERING_SERVICE_URL
      value: https://cics-q1.adeo.no/oppdrag/simulerFpServiceWSBinding

