apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: tbd
  name: spenn-avstemming
  namespace: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    initialDelay: 10
    path: /isalive
  readiness:
    initialDelay: 10
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  preStopHook:
    http:
      path: /stop
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 50m
      memory: 64Mi
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: db-custom-1-3840
        name: spenn-avstemming
        databases:
          - name: spenn-avstemming
            envVarPrefix: DATABASE
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
  envFrom:
    - secret: spenn
  accessPolicy:
    outbound:
      external:
        - host: mpls02.adeo.no
          ports:
            - port: 1414
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spenn-avstemming-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_RESET_POLICY
      value: latest
    - name: MQ_HOSTNAME
      value: mpls02.adeo.no
    - name: MQ_CHANNEL
      value: P_SPENN
    - name: MQ_PORT
      value: "1414"
    - name: MQ_QUEUE_MANAGER
      value: MPLS02
    - name: AVSTEMMING_QUEUE_SEND
      # Setter target client = 1 for bakoverkompabilitet med stormaskin
      value: queue:///QA.P234.OB29_AVSTEMMING_XML?targetClient=1
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
