apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: tbd
  name: spenn-mq
  namespace: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    initialDelay: 10
    path: /isalive
  readiness:
    initialDelay: 10
    path: /isready
  preStopHook:
    http:
      path: /stop
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 64Mi
  kafka:
    pool: nav-prod
  accessPolicy:
    outbound:
      external:
        - host: mpls02.adeo.no
          ports:
            - port: 1414
  secureLogs:
    enabled: true
  envFrom:
    - secret: spenn
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spenn-mq-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_RESET_POLICY
      value: none
    - name: MQ_HOSTNAME
      value: mpls02.adeo.no
    - name: MQ_CHANNEL
      value: P_SPENN
    - name: MQ_PORT
      value: "1414"
    - name: MQ_QUEUE_MANAGER
      value: MPLS02
    - name: OPPDRAG_QUEUE_SEND
      value: QA.P231.OB04_OPPDRAG_XML
    - name: OPPDRAG_QUEUE_MOTTAK
      value: QA.P_SPENN.OPPDRAG_SP_XML_KVITT
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
