apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: tbd
  name: spenn
  namespace: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    initialDelay: 10
    path: /isalive
  readiness:
    initialDelay: 10
    path: /isready
  preStopHook:
    http:
      path: /stop
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    max: 6
    min: 2
    scalingStrategy:
      kafka:
        topic: tbd.rapid.v1
        consumerGroup: tbd-spenn-v1
        threshold: 200
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 64Mi
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: db-custom-4-16384
        name: spenn
        databases:
          - name: spenn
            envVarPrefix: DATABASE
            users:
              - name: spenn-opprydding
        flags:
          - name: cloudsql.enable_pgaudit
            value: "true"
          - name: pgaudit.log
            value: 'write'
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spenn-v1
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_RESET_POLICY
      value: none
