/*
 * This file is generated by jOOQ.
 */
package no.nav.helse.spenn.jooq;


import javax.annotation.processing.Generated;

import no.nav.helse.spenn.jooq.tables.Oppdrag;
import no.nav.helse.spenn.jooq.tables.Transaksjon;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index OPPDRAG_MODIFIED_IDX = Indexes0.OPPDRAG_MODIFIED_IDX;
    public static final Index OPPDRAG_UTBETALINGSREFERANSE_KEY = Indexes0.OPPDRAG_UTBETALINGSREFERANSE_KEY;
    public static final Index PK_OPPDRAG = Indexes0.PK_OPPDRAG;
    public static final Index UQ_OPPDRAG_SAKSKOMPLEKS_ID = Indexes0.UQ_OPPDRAG_SAKSKOMPLEKS_ID;
    public static final Index TRANSAKSJON_PKEY = Indexes0.TRANSAKSJON_PKEY;
    public static final Index TRANSAKSJON_STATUS_IDX = Indexes0.TRANSAKSJON_STATUS_IDX;
    public static final Index UQ_TRANSAKSJON_NOKKEL = Indexes0.UQ_TRANSAKSJON_NOKKEL;
    public static final Index UQ_TRANSAKSJON_OPPDRAG_ID = Indexes0.UQ_TRANSAKSJON_OPPDRAG_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index OPPDRAG_MODIFIED_IDX = Internal.createIndex("oppdrag_modified_idx", Oppdrag.OPPDRAG, new OrderField[] { Oppdrag.OPPDRAG.MODIFIED }, false);
        public static Index OPPDRAG_UTBETALINGSREFERANSE_KEY = Internal.createIndex("oppdrag_utbetalingsreferanse_key", Oppdrag.OPPDRAG, new OrderField[] { Oppdrag.OPPDRAG.UTBETALINGSREFERANSE }, true);
        public static Index PK_OPPDRAG = Internal.createIndex("pk_oppdrag", Oppdrag.OPPDRAG, new OrderField[] { Oppdrag.OPPDRAG.ID }, true);
        public static Index UQ_OPPDRAG_SAKSKOMPLEKS_ID = Internal.createIndex("uq_oppdrag_sakskompleks_id", Oppdrag.OPPDRAG, new OrderField[] { Oppdrag.OPPDRAG.SAKSKOMPLEKS_ID }, true);
        public static Index TRANSAKSJON_PKEY = Internal.createIndex("transaksjon_pkey", Transaksjon.TRANSAKSJON, new OrderField[] { Transaksjon.TRANSAKSJON.ID }, true);
        public static Index TRANSAKSJON_STATUS_IDX = Internal.createIndex("transaksjon_status_idx", Transaksjon.TRANSAKSJON, new OrderField[] { Transaksjon.TRANSAKSJON.STATUS }, false);
        public static Index UQ_TRANSAKSJON_NOKKEL = Internal.createIndex("uq_transaksjon_nokkel", Transaksjon.TRANSAKSJON, new OrderField[] { Transaksjon.TRANSAKSJON.NOKKEL }, true);
        public static Index UQ_TRANSAKSJON_OPPDRAG_ID = Internal.createIndex("uq_transaksjon_oppdrag_id", Transaksjon.TRANSAKSJON, new OrderField[] { Transaksjon.TRANSAKSJON.OPPDRAG_ID }, true);
    }
}
