/*
 * This file is generated by jOOQ.
 */
package no.nav.helse.spenn.jooq;


import javax.annotation.processing.Generated;

import no.nav.helse.spenn.jooq.tables.Avstemming;
import no.nav.helse.spenn.jooq.tables.Oppdragstate;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AVSTEMMING_PKEY = Indexes0.AVSTEMMING_PKEY;
    public static final Index UQ_AVSTEMMING_NOKKEL = Indexes0.UQ_AVSTEMMING_NOKKEL;
    public static final Index UQ_AVSTEMMING_OPPDRAGSTATE = Indexes0.UQ_AVSTEMMING_OPPDRAGSTATE;
    public static final Index OPPDRAGSTATE_MODIFIED_IDX = Indexes0.OPPDRAGSTATE_MODIFIED_IDX;
    public static final Index OPPDRAGSTATE_STATUS_IDX = Indexes0.OPPDRAGSTATE_STATUS_IDX;
    public static final Index PK_OPPDRAGSTATE = Indexes0.PK_OPPDRAGSTATE;
    public static final Index UQ_SAKSKOMPLEKS_ID = Indexes0.UQ_SAKSKOMPLEKS_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AVSTEMMING_PKEY = Internal.createIndex("avstemming_pkey", Avstemming.AVSTEMMING, new OrderField[] { Avstemming.AVSTEMMING.ID }, true);
        public static Index UQ_AVSTEMMING_NOKKEL = Internal.createIndex("uq_avstemming_nokkel", Avstemming.AVSTEMMING, new OrderField[] { Avstemming.AVSTEMMING.NOKKEL }, true);
        public static Index UQ_AVSTEMMING_OPPDRAGSTATE = Internal.createIndex("uq_avstemming_oppdragstate", Avstemming.AVSTEMMING, new OrderField[] { Avstemming.AVSTEMMING.OPPDRAGSTATE_ID }, true);
        public static Index OPPDRAGSTATE_MODIFIED_IDX = Internal.createIndex("oppdragstate_modified_idx", Oppdragstate.OPPDRAGSTATE, new OrderField[] { Oppdragstate.OPPDRAGSTATE.MODIFIED }, false);
        public static Index OPPDRAGSTATE_STATUS_IDX = Internal.createIndex("oppdragstate_status_idx", Oppdragstate.OPPDRAGSTATE, new OrderField[] { Oppdragstate.OPPDRAGSTATE.STATUS }, false);
        public static Index PK_OPPDRAGSTATE = Internal.createIndex("pk_oppdragstate", Oppdragstate.OPPDRAGSTATE, new OrderField[] { Oppdragstate.OPPDRAGSTATE.ID }, true);
        public static Index UQ_SAKSKOMPLEKS_ID = Internal.createIndex("uq_sakskompleks_id", Oppdragstate.OPPDRAGSTATE, new OrderField[] { Oppdragstate.OPPDRAGSTATE.SAKSKOMPLEKS_ID }, true);
    }
}
