/*
 * This file is generated by jOOQ.
 */
package no.nav.helse.spenn.jooq;


import javax.annotation.Generated;

import no.nav.helse.spenn.jooq.tables.Avstemming;
import no.nav.helse.spenn.jooq.tables.Oppdragstate;
import no.nav.helse.spenn.jooq.tables.records.AvstemmingRecord;
import no.nav.helse.spenn.jooq.tables.records.OppdragstateRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.12"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AvstemmingRecord, Long> IDENTITY_AVSTEMMING = Identities0.IDENTITY_AVSTEMMING;
    public static final Identity<OppdragstateRecord, Long> IDENTITY_OPPDRAGSTATE = Identities0.IDENTITY_OPPDRAGSTATE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AvstemmingRecord> AVSTEMMING_PKEY = UniqueKeys0.AVSTEMMING_PKEY;
    public static final UniqueKey<AvstemmingRecord> UQ_AVSTEMMING_OPPDRAGSTATE = UniqueKeys0.UQ_AVSTEMMING_OPPDRAGSTATE;
    public static final UniqueKey<AvstemmingRecord> UQ_AVSTEMMING_NOKKEL = UniqueKeys0.UQ_AVSTEMMING_NOKKEL;
    public static final UniqueKey<OppdragstateRecord> PK_OPPDRAGSTATE = UniqueKeys0.PK_OPPDRAGSTATE;
    public static final UniqueKey<OppdragstateRecord> UQ_SOKNAD_ID = UniqueKeys0.UQ_SOKNAD_ID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AvstemmingRecord, OppdragstateRecord> AVSTEMMING__AVSTEMMING_OPPDRAGSTATE_ID_FKEY = ForeignKeys0.AVSTEMMING__AVSTEMMING_OPPDRAGSTATE_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AvstemmingRecord, Long> IDENTITY_AVSTEMMING = Internal.createIdentity(Avstemming.AVSTEMMING, Avstemming.AVSTEMMING.ID);
        public static Identity<OppdragstateRecord, Long> IDENTITY_OPPDRAGSTATE = Internal.createIdentity(Oppdragstate.OPPDRAGSTATE, Oppdragstate.OPPDRAGSTATE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AvstemmingRecord> AVSTEMMING_PKEY = Internal.createUniqueKey(Avstemming.AVSTEMMING, "avstemming_pkey", Avstemming.AVSTEMMING.ID);
        public static final UniqueKey<AvstemmingRecord> UQ_AVSTEMMING_OPPDRAGSTATE = Internal.createUniqueKey(Avstemming.AVSTEMMING, "uq_avstemming_oppdragstate", Avstemming.AVSTEMMING.OPPDRAGSTATE_ID);
        public static final UniqueKey<AvstemmingRecord> UQ_AVSTEMMING_NOKKEL = Internal.createUniqueKey(Avstemming.AVSTEMMING, "uq_avstemming_nokkel", Avstemming.AVSTEMMING.NOKKEL);
        public static final UniqueKey<OppdragstateRecord> PK_OPPDRAGSTATE = Internal.createUniqueKey(Oppdragstate.OPPDRAGSTATE, "pk_oppdragstate", Oppdragstate.OPPDRAGSTATE.ID);
        public static final UniqueKey<OppdragstateRecord> UQ_SOKNAD_ID = Internal.createUniqueKey(Oppdragstate.OPPDRAGSTATE, "uq_soknad_id", Oppdragstate.OPPDRAGSTATE.SOKNAD_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<AvstemmingRecord, OppdragstateRecord> AVSTEMMING__AVSTEMMING_OPPDRAGSTATE_ID_FKEY = Internal.createForeignKey(no.nav.helse.spenn.jooq.Keys.PK_OPPDRAGSTATE, Avstemming.AVSTEMMING, "avstemming__avstemming_oppdragstate_id_fkey", Avstemming.AVSTEMMING.OPPDRAGSTATE_ID);
    }
}
