/*
 * This file is generated by jOOQ.
 */
package no.nav.helse.spenn.jooq;


import javax.annotation.processing.Generated;

import no.nav.helse.spenn.jooq.tables.Avstemming;
import no.nav.helse.spenn.jooq.tables.Oppdragstate;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.avstemming</code>.
     */
    public static final Avstemming AVSTEMMING = Avstemming.AVSTEMMING;

    /**
     * The table <code>public.oppdragstate</code>.
     */
    public static final Oppdragstate OPPDRAGSTATE = Oppdragstate.OPPDRAGSTATE;
}
