/*
 * This file is generated by jOOQ.
 */
package no.nav.helse.spenn.jooq;


import javax.annotation.processing.Generated;

import no.nav.helse.spenn.jooq.tables.Oppdrag;
import no.nav.helse.spenn.jooq.tables.Transaksjon;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.oppdrag</code>.
     */
    public static final Oppdrag OPPDRAG = Oppdrag.OPPDRAG;

    /**
     * The table <code>public.transaksjon</code>.
     */
    public static final Transaksjon TRANSAKSJON = Transaksjon.TRANSAKSJON;
}
