package no.nav.helse.spenn.metrics


val VEDTAK = "VEDTAK"
val SIMULERING = "SIMULERING"
val OPPDRAG = "OPPDRAG"
val SIMULERING_UTBETALT_TOTAL_BELOP = "SIMULERING_UTBETALT_TOTAL_BELOP"
val SIMULERING_UTBETALT_BELOP = "SIMULERING_UTBETALT_BELOP"
