package no.nav.helse.spenn.metrics


val VEDTAK = "VEDTAK"
val SIMULERING = "SIMULERING"
val OPPDRAG = "OPPDRAG"
val SIMULERING_UTBETALT_BELOP = "SIMULERING_UTBETALT_BELOP"
val SIMULERING_UTBETALT_MAKS_BELOP = "SIMULERING_UTBETALT_MAKS_BELOP"
val SENDT_TIL_OS = "SEND_TIL_OS"
val AVSTEMMING = "AVSTEMMING"
