
package no.nav.system.os.eksponering.simulerfpservicewsbinding;

import jakarta.xml.ws.WebFault;
import no.nav.system.os.tjenester.simulerfpservice.feil.FeilUnderBehandling;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "simulerBeregningFeilUnderBehandling", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt")
public class SimulerBeregningFeilUnderBehandling
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FeilUnderBehandling faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SimulerBeregningFeilUnderBehandling(String message, FeilUnderBehandling faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SimulerBeregningFeilUnderBehandling(String message, FeilUnderBehandling faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: no.nav.system.os.tjenester.simulerfpservice.feil.FeilUnderBehandling
     */
    public FeilUnderBehandling getFaultInfo() {
        return faultInfo;
    }

}
