
package no.nav.system.os.eksponering.simulerfpservicewsbinding;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import no.nav.system.os.tjenester.simulerfpservice.simulerfpservicegrensesnitt.SendInnOppdragRequest;
import no.nav.system.os.tjenester.simulerfpservice.simulerfpservicegrensesnitt.SimulerBeregningRequest;
import no.nav.system.os.tjenester.simulerfpservice.simulerfpservicegrensesnitt.SimulerBeregningResponse;
import no.nav.system.os.tjenester.simulerfpservice.simulerfpserviceservicetypes.ObjectFactory;
import no.nav.system.os.tjenester.simulerfpservice.simulerfpservicegrensesnitt.SendInnOppdragResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "simulerFpService", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class,
    no.nav.system.os.entiteter.beregningskjema.ObjectFactory.class,
    no.nav.system.os.entiteter.infomelding.ObjectFactory.class,
    no.nav.system.os.entiteter.oppdragskjema.ObjectFactory.class,
    no.nav.system.os.tjenester.simulerfpservice.feil.ObjectFactory.class,
    no.nav.system.os.tjenester.simulerfpservice.simulerfpservicegrensesnitt.ObjectFactory.class,
    no.nav.system.os.entiteter.typer.simpletypes.ObjectFactory.class
})
public interface SimulerFpService {


    /**
     * Operasjonen tilbyr innsending og registrering av ny/endret oppdrag som følge av nytt/endring på vedtak
     * 
     * @param parameters
     * @return
     *     returns no.nav.system.os.tjenester.simulerfpservice.simulerfpservicegrensesnitt.SendInnOppdragResponse
     * @throws SendInnOppdragFeilUnderBehandling
     */
    @WebMethod
    @WebResult(name = "sendInnOppdragResponse", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt", partName = "parameters")
    public SendInnOppdragResponse sendInnOppdrag(
        @WebParam(name = "sendInnOppdragRequest", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt", partName = "parameters")
        SendInnOppdragRequest parameters)
        throws SendInnOppdragFeilUnderBehandling
    ;

    /**
     * Operasjonen tilbyr simuleringsberegning
     * 
     * @param parameters
     * @return
     *     returns no.nav.system.os.tjenester.simulerfpservice.simulerfpservicegrensesnitt.SimulerBeregningResponse
     * @throws SimulerBeregningFeilUnderBehandling
     */
    @WebMethod
    @WebResult(name = "simulerBeregningResponse", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt", partName = "parameters")
    public SimulerBeregningResponse simulerBeregning(
        @WebParam(name = "simulerBeregningRequest", targetNamespace = "http://nav.no/system/os/tjenester/simulerFpService/simulerFpServiceGrensesnitt", partName = "parameters")
        SimulerBeregningRequest parameters)
        throws SimulerBeregningFeilUnderBehandling
    ;

}
