//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import jakarta.xml.bind.annotation.*;


/**
 * Inneholder elementene som skal være med i en 610-rekord, Avstemming
 * 
 * <p>Java class for avstemming-610 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="avstemming-610"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kodeAksjon"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="A"/&gt;
 *               &lt;enumeration value="B"/&gt;
 *               &lt;enumeration value="C"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="kodeFagomraade" type="{http://www.trygdeetaten.no/skjema/oppdrag}TkodeFagomraade" minOccurs="0"/&gt;
 *         &lt;element name="avstemmingId" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="11"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="oppdrag-110" type="{http://www.trygdeetaten.no/skjema/oppdrag}oppdrag-110" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "avstemming-610", propOrder = {
    "kodeAksjon",
    "kodeFagomraade",
    "avstemmingId",
    "oppdrag110"
})
public class Avstemming610 {

    @XmlElement(required = true)
    protected String kodeAksjon;
    protected String kodeFagomraade;
    protected String avstemmingId;
    @XmlElement(name = "oppdrag-110")
    protected no.nav.trygdeetaten.skjema.oppdrag.Oppdrag110 oppdrag110;

    /**
     * Gets the value of the kodeAksjon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeAksjon() {
        return kodeAksjon;
    }

    /**
     * Sets the value of the kodeAksjon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeAksjon(String value) {
        this.kodeAksjon = value;
    }

    /**
     * Gets the value of the kodeFagomraade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeFagomraade() {
        return kodeFagomraade;
    }

    /**
     * Sets the value of the kodeFagomraade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeFagomraade(String value) {
        this.kodeFagomraade = value;
    }

    /**
     * Gets the value of the avstemmingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvstemmingId() {
        return avstemmingId;
    }

    /**
     * Sets the value of the avstemmingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvstemmingId(String value) {
        this.avstemmingId = value;
    }

    /**
     * Gets the value of the oppdrag110 property.
     * 
     * @return
     *     possible object is
     *     {@link no.nav.trygdeetaten.skjema.oppdrag.Oppdrag110 }
     *     
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Oppdrag110 getOppdrag110() {
        return oppdrag110;
    }

    /**
     * Sets the value of the oppdrag110 property.
     * 
     * @param value
     *     allowed object is
     *     {@link no.nav.trygdeetaten.skjema.oppdrag.Oppdrag110 }
     *     
     */
    public void setOppdrag110(no.nav.trygdeetaten.skjema.oppdrag.Oppdrag110 value) {
        this.oppdrag110 = value;
    }

    public Avstemming610 withKodeAksjon(String value) {
        setKodeAksjon(value);
        return this;
    }

    public Avstemming610 withKodeFagomraade(String value) {
        setKodeFagomraade(value);
        return this;
    }

    public Avstemming610 withAvstemmingId(String value) {
        setAvstemmingId(value);
        return this;
    }

    public Avstemming610 withOppdrag110(Oppdrag110 value) {
        setOppdrag110(value);
        return this;
    }

}
