//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import jakarta.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Inneholder elementene som skal være med i en input 195-rekord, Hent oppdrag
 *             
 * 
 * <p>Java class for hent-oppdrag-195 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hent-oppdrag-195"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kodeAksjon" type="{http://www.trygdeetaten.no/skjema/oppdrag}hent-oppdrag-195-kodeAksjon"/&gt;
 *         &lt;element name="kodeFagomraade" type="{http://www.trygdeetaten.no/skjema/oppdrag}TkodeFagomraade" minOccurs="0"/&gt;
 *         &lt;element name="fagsystemId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfagsystemId" minOccurs="0"/&gt;
 *         &lt;element name="oppdragsId" type="{http://www.trygdeetaten.no/skjema/oppdrag}ToppdragsId" minOccurs="0"/&gt;
 *         &lt;element name="oppdragGjelderId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfnrOrgnr" minOccurs="0"/&gt;
 *         &lt;element name="datoFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="datoTom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hent-oppdrag-195", propOrder = {
    "kodeAksjon",
    "kodeFagomraade",
    "fagsystemId",
    "oppdragsId",
    "oppdragGjelderId",
    "datoFom",
    "datoTom"
})
public class HentOppdrag195 {

    @XmlElement(required = true)
    protected String kodeAksjon;
    protected String kodeFagomraade;
    protected String fagsystemId;
    protected Long oppdragsId;
    protected String oppdragGjelderId;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoFom;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoTom;

    /**
     * Gets the value of the kodeAksjon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeAksjon() {
        return kodeAksjon;
    }

    /**
     * Sets the value of the kodeAksjon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeAksjon(String value) {
        this.kodeAksjon = value;
    }

    /**
     * Gets the value of the kodeFagomraade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeFagomraade() {
        return kodeFagomraade;
    }

    /**
     * Sets the value of the kodeFagomraade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeFagomraade(String value) {
        this.kodeFagomraade = value;
    }

    /**
     * Gets the value of the fagsystemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFagsystemId() {
        return fagsystemId;
    }

    /**
     * Sets the value of the fagsystemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFagsystemId(String value) {
        this.fagsystemId = value;
    }

    /**
     * Gets the value of the oppdragsId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOppdragsId() {
        return oppdragsId;
    }

    /**
     * Sets the value of the oppdragsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOppdragsId(Long value) {
        this.oppdragsId = value;
    }

    /**
     * Gets the value of the oppdragGjelderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOppdragGjelderId() {
        return oppdragGjelderId;
    }

    /**
     * Sets the value of the oppdragGjelderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOppdragGjelderId(String value) {
        this.oppdragGjelderId = value;
    }

    /**
     * Gets the value of the datoFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoFom() {
        return datoFom;
    }

    /**
     * Sets the value of the datoFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoFom(XMLGregorianCalendar value) {
        this.datoFom = value;
    }

    /**
     * Gets the value of the datoTom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoTom() {
        return datoTom;
    }

    /**
     * Sets the value of the datoTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoTom(XMLGregorianCalendar value) {
        this.datoTom = value;
    }

    public HentOppdrag195 withKodeAksjon(String value) {
        setKodeAksjon(value);
        return this;
    }

    public HentOppdrag195 withKodeFagomraade(String value) {
        setKodeFagomraade(value);
        return this;
    }

    public HentOppdrag195 withFagsystemId(String value) {
        setFagsystemId(value);
        return this;
    }

    public HentOppdrag195 withOppdragsId(Long value) {
        setOppdragsId(value);
        return this;
    }

    public HentOppdrag195 withOppdragGjelderId(String value) {
        setOppdragGjelderId(value);
        return this;
    }

    public HentOppdrag195 withDatoFom(XMLGregorianCalendar value) {
        setDatoFom(value);
        return this;
    }

    public HentOppdrag195 withDatoTom(XMLGregorianCalendar value) {
        setDatoTom(value);
        return this;
    }

}
