//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Inneholder elementene som skal være med i en input 158-rekord
 * 
 * <p>Java class for linje-tekst-158 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="linje-tekst-158"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tekstLnr" type="{http://www.trygdeetaten.no/skjema/oppdrag}TtekstLnr"/&gt;
 *         &lt;element name="tekstKode" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="tekst" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="40"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="datoTekstFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato"/&gt;
 *         &lt;element name="datoTekstTom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="feilreg" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tfeilreg" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "linje-tekst-158", propOrder = {
    "tekstLnr",
    "tekstKode",
    "tekst",
    "datoTekstFom",
    "datoTekstTom",
    "feilreg"
})
public class LinjeTekst158 {

    @XmlElement(required = true)
    protected BigInteger tekstLnr;
    protected String tekstKode;
    protected String tekst;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoTekstFom;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoTekstTom;
    protected String feilreg;

    /**
     * Gets the value of the tekstLnr property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTekstLnr() {
        return tekstLnr;
    }

    /**
     * Sets the value of the tekstLnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTekstLnr(BigInteger value) {
        this.tekstLnr = value;
    }

    /**
     * Gets the value of the tekstKode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTekstKode() {
        return tekstKode;
    }

    /**
     * Sets the value of the tekstKode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTekstKode(String value) {
        this.tekstKode = value;
    }

    /**
     * Gets the value of the tekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTekst() {
        return tekst;
    }

    /**
     * Sets the value of the tekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTekst(String value) {
        this.tekst = value;
    }

    /**
     * Gets the value of the datoTekstFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoTekstFom() {
        return datoTekstFom;
    }

    /**
     * Sets the value of the datoTekstFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoTekstFom(XMLGregorianCalendar value) {
        this.datoTekstFom = value;
    }

    /**
     * Gets the value of the datoTekstTom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoTekstTom() {
        return datoTekstTom;
    }

    /**
     * Sets the value of the datoTekstTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoTekstTom(XMLGregorianCalendar value) {
        this.datoTekstTom = value;
    }

    /**
     * Gets the value of the feilreg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeilreg() {
        return feilreg;
    }

    /**
     * Sets the value of the feilreg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeilreg(String value) {
        this.feilreg = value;
    }

    public LinjeTekst158 withTekstLnr(BigInteger value) {
        setTekstLnr(value);
        return this;
    }

    public LinjeTekst158 withTekstKode(String value) {
        setTekstKode(value);
        return this;
    }

    public LinjeTekst158 withTekst(String value) {
        setTekst(value);
        return this;
    }

    public LinjeTekst158 withDatoTekstFom(XMLGregorianCalendar value) {
        setDatoTekstFom(value);
        return this;
    }

    public LinjeTekst158 withDatoTekstTom(XMLGregorianCalendar value) {
        setDatoTekstTom(value);
        return this;
    }

    public LinjeTekst158 withFeilreg(String value) {
        setFeilreg(value);
        return this;
    }

}
