//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import jakarta.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Inneholder elementene som skal være med i en output 151-rekord, linjestatus
 *             
 * 
 * <p>Java class for linje-status-151 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="linje-status-151"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kodeStatusLinje" type="{http://www.trygdeetaten.no/skjema/oppdrag}TkodeStatusLinje"/&gt;
 *         &lt;element name="datoStatusFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato"/&gt;
 *         &lt;element name="tidspktReg" type="{http://www.trygdeetaten.no/skjema/oppdrag}TtidspktReg"/&gt;
 *         &lt;element name="saksbehId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TsaksbehId"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "linje-status-151", propOrder = {
    "kodeStatusLinje",
    "datoStatusFom",
    "tidspktReg",
    "saksbehId"
})
public class LinjeStatus151 {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TkodeStatusLinje kodeStatusLinje;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoStatusFom;
    @XmlElement(required = true)
    protected String tidspktReg;
    @XmlElement(required = true)
    protected String saksbehId;

    /**
     * Gets the value of the kodeStatusLinje property.
     * 
     * @return
     *     possible object is
     *     {@link TkodeStatusLinje }
     *     
     */
    public TkodeStatusLinje getKodeStatusLinje() {
        return kodeStatusLinje;
    }

    /**
     * Sets the value of the kodeStatusLinje property.
     * 
     * @param value
     *     allowed object is
     *     {@link TkodeStatusLinje }
     *     
     */
    public void setKodeStatusLinje(TkodeStatusLinje value) {
        this.kodeStatusLinje = value;
    }

    /**
     * Gets the value of the datoStatusFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoStatusFom() {
        return datoStatusFom;
    }

    /**
     * Sets the value of the datoStatusFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoStatusFom(XMLGregorianCalendar value) {
        this.datoStatusFom = value;
    }

    /**
     * Gets the value of the tidspktReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTidspktReg() {
        return tidspktReg;
    }

    /**
     * Sets the value of the tidspktReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTidspktReg(String value) {
        this.tidspktReg = value;
    }

    /**
     * Gets the value of the saksbehId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaksbehId() {
        return saksbehId;
    }

    /**
     * Sets the value of the saksbehId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaksbehId(String value) {
        this.saksbehId = value;
    }

    public LinjeStatus151 withKodeStatusLinje(TkodeStatusLinje value) {
        setKodeStatusLinje(value);
        return this;
    }

    public LinjeStatus151 withDatoStatusFom(XMLGregorianCalendar value) {
        setDatoStatusFom(value);
        return this;
    }

    public LinjeStatus151 withTidspktReg(String value) {
        setTidspktReg(value);
        return this;
    }

    public LinjeStatus151 withSaksbehId(String value) {
        setSaksbehId(value);
        return this;
    }

}
