//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.trygdeetaten.skjema.oppdrag package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Oppdrag_QNAME = new QName("http://www.trygdeetaten.no/skjema/oppdrag", "no/nav/trygdeetaten/skjema/oppdrag");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.trygdeetaten.skjema.oppdrag
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Oppdrag }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Oppdrag createOppdrag() {
        return new no.nav.trygdeetaten.skjema.oppdrag.Oppdrag();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Valuta190 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Valuta190 createValuta190() {
        return new Valuta190();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.UtbetalesTil155 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.UtbetalesTil155 createUtbetalesTil155() {
        return new UtbetalesTil155();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Tekst140 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Tekst140 createTekst140() {
        return new Tekst140();
    }

    /**
     * Create an instance of {@link Skyldner153 }
     * 
     */
    public Skyldner153 createSkyldner153() {
        return new Skyldner153();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.SimuleringsStoppNivaa }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.SimuleringsStoppNivaa createSimuleringsStoppNivaa() {
        return new SimuleringsStoppNivaa();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.SimuleringsResultat301 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.SimuleringsResultat301 createSimuleringsResultat301() {
        return new SimuleringsResultat301();
    }

    /**
     * Create an instance of {@link SimuleringsResultat }
     * 
     */
    public SimuleringsResultat createSimuleringsResultat() {
        return new SimuleringsResultat();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.SimuleringsPerioder }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.SimuleringsPerioder createSimuleringsPerioder() {
        return new SimuleringsPerioder();
    }

    /**
     * Create an instance of {@link SimuleringsPeriode300 }
     * 
     */
    public SimuleringsPeriode300 createSimuleringsPeriode300() {
        return new SimuleringsPeriode300();
    }

    /**
     * Create an instance of {@link SimuleringsLinjer }
     * 
     */
    public SimuleringsLinjer createSimuleringsLinjer() {
        return new SimuleringsLinjer();
    }

    /**
     * Create an instance of {@link OppdragsStatus111 }
     * 
     */
    public OppdragsStatus111 createOppdragsStatus111() {
        return new OppdragsStatus111();
    }

    /**
     * Create an instance of {@link OppdragGjelder112 }
     * 
     */
    public OppdragGjelder112 createOppdragGjelder112() {
        return new OppdragGjelder112();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.LinjeTekst158 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.LinjeTekst158 createLinjeTekst158() {
        return new LinjeTekst158();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.LinjeStatus151 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.LinjeStatus151 createLinjeStatus151() {
        return new LinjeStatus151();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.LinjeEnhet160 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.LinjeEnhet160 createLinjeEnhet160() {
        return new LinjeEnhet160();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Klassifikasjon152 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Klassifikasjon152 createKlassifikasjon152() {
        return new Klassifikasjon152();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Kid154 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Kid154 createKid154() {
        return new Kid154();
    }

    /**
     * Create an instance of {@link HentOppdrag195 }
     * 
     */
    public HentOppdrag195 createHentOppdrag195() {
        return new HentOppdrag195();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Grad170 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Grad170 createGrad170() {
        return new Grad170();
    }

    /**
     * Create an instance of {@link SimuleringsResultatLinje301 }
     * 
     */
    public SimuleringsResultatLinje301 createSimuleringsResultatLinje301() {
        return new SimuleringsResultatLinje301();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.OppdragsEnhet120 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.OppdragsEnhet120 createOppdragsEnhet120() {
        return new OppdragsEnhet120();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Bilagstype113 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Bilagstype113 createBilagstype113() {
        return new Bilagstype113();
    }

    /**
     * Create an instance of {@link BelopsGrense130 }
     * 
     */
    public BelopsGrense130 createBelopsGrense130() {
        return new BelopsGrense130();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Avstemming610 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Avstemming610 createAvstemming610() {
        return new Avstemming610();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Avstemming115 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Avstemming115 createAvstemming115() {
        return new Avstemming115();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Ompostering116 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Ompostering116 createOmpostering116() {
        return new Ompostering116();
    }

    /**
     * Create an instance of {@link Attestant180 }
     * 
     */
    public Attestant180 createAttestant180() {
        return new Attestant180();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.OppdragsLinje150 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.OppdragsLinje150 createOppdragsLinje150() {
        return new OppdragsLinje150();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Oppdrag110 }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Oppdrag110 createOppdrag110() {
        return new Oppdrag110();
    }

    /**
     * Create an instance of {@link no.nav.trygdeetaten.skjema.oppdrag.Mmel }
     * 
     */
    public no.nav.trygdeetaten.skjema.oppdrag.Mmel createMmel() {
        return new Mmel();
    }

    /**
     * Create an instance of {@link Refusjonsinfo156 }
     * 
     */
    public Refusjonsinfo156 createRefusjonsinfo156() {
        return new Refusjonsinfo156();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link no.nav.trygdeetaten.skjema.oppdrag.Oppdrag }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link no.nav.trygdeetaten.skjema.oppdrag.Oppdrag }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.trygdeetaten.no/skjema/oppdrag", name = "no/nav/trygdeetaten/skjema/oppdrag")
    public JAXBElement<Oppdrag> createOppdrag(no.nav.trygdeetaten.skjema.oppdrag.Oppdrag value) {
        return new JAXBElement<no.nav.trygdeetaten.skjema.oppdrag.Oppdrag>(_Oppdrag_QNAME, Oppdrag.class, null, value);
    }

}
