//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import jakarta.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Ompostering - Referanse ID 116
 * 
 * <p>Java class for ompostering-116 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ompostering-116"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="omPostering" type="{http://www.trygdeetaten.no/skjema/oppdrag}TJaNei"/&gt;
 *         &lt;element name="datoOmposterFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="feilreg" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tfeilreg" minOccurs="0"/&gt;
 *         &lt;element name="tidspktReg" type="{http://www.trygdeetaten.no/skjema/oppdrag}TtidspktReg"/&gt;
 *         &lt;element name="saksbehId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TsaksbehId"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ompostering-116", propOrder = {
    "omPostering",
    "datoOmposterFom",
    "feilreg",
    "tidspktReg",
    "saksbehId"
})
public class Ompostering116 {

    @XmlElement(required = true)
    protected String omPostering;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoOmposterFom;
    protected String feilreg;
    @XmlElement(required = true)
    protected String tidspktReg;
    @XmlElement(required = true)
    protected String saksbehId;

    /**
     * Gets the value of the omPostering property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOmPostering() {
        return omPostering;
    }

    /**
     * Sets the value of the omPostering property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOmPostering(String value) {
        this.omPostering = value;
    }

    /**
     * Gets the value of the datoOmposterFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoOmposterFom() {
        return datoOmposterFom;
    }

    /**
     * Sets the value of the datoOmposterFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoOmposterFom(XMLGregorianCalendar value) {
        this.datoOmposterFom = value;
    }

    /**
     * Gets the value of the feilreg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeilreg() {
        return feilreg;
    }

    /**
     * Sets the value of the feilreg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeilreg(String value) {
        this.feilreg = value;
    }

    /**
     * Gets the value of the tidspktReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTidspktReg() {
        return tidspktReg;
    }

    /**
     * Sets the value of the tidspktReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTidspktReg(String value) {
        this.tidspktReg = value;
    }

    /**
     * Gets the value of the saksbehId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaksbehId() {
        return saksbehId;
    }

    /**
     * Sets the value of the saksbehId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaksbehId(String value) {
        this.saksbehId = value;
    }

    public Ompostering116 withOmPostering(String value) {
        setOmPostering(value);
        return this;
    }

    public Ompostering116 withDatoOmposterFom(XMLGregorianCalendar value) {
        setDatoOmposterFom(value);
        return this;
    }

    public Ompostering116 withFeilreg(String value) {
        setFeilreg(value);
        return this;
    }

    public Ompostering116 withTidspktReg(String value) {
        setTidspktReg(value);
        return this;
    }

    public Ompostering116 withSaksbehId(String value) {
        setSaksbehId(value);
        return this;
    }

}
