//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Inneholder elementene som skal være med i en 150-rekord, Oppdragslinje
 *             
 * 
 * <p>Java class for oppdrags-linje-150 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="oppdrags-linje-150"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="kodeEndringLinje"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="NY"/&gt;
 *               &lt;enumeration value="ENDR"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="kodeStatusLinje" type="{http://www.trygdeetaten.no/skjema/oppdrag}TkodeStatusLinje" minOccurs="0"/&gt;
 *         &lt;element name="datoStatusFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="vedtakId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TvedtakId" minOccurs="0"/&gt;
 *         &lt;element name="delytelseId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TdelytelseId" minOccurs="0"/&gt;
 *         &lt;element name="linjeId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TlinjeId" minOccurs="0"/&gt;
 *         &lt;element name="kodeKlassifik" type="{http://www.trygdeetaten.no/skjema/oppdrag}TkodeKlassifik"/&gt;
 *         &lt;element name="datoKlassifikFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="datoVedtakFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato"/&gt;
 *         &lt;element name="datoVedtakTom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="sats" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tsats"/&gt;
 *         &lt;element name="fradragTillegg" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfradragTillegg"/&gt;
 *         &lt;element name="typeSats" type="{http://www.trygdeetaten.no/skjema/oppdrag}TtypeSats"/&gt;
 *         &lt;element name="skyldnerId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfnrOrgnr" minOccurs="0"/&gt;
 *         &lt;element name="datoSkyldnerFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="kravhaverId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfnrOrgnr" minOccurs="0"/&gt;
 *         &lt;element name="datoKravhaverFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="kid" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tkid" minOccurs="0"/&gt;
 *         &lt;element name="datoKidFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="brukKjoreplan" type="{http://www.trygdeetaten.no/skjema/oppdrag}TbrukKjoreplan" minOccurs="0"/&gt;
 *         &lt;element name="saksbehId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TsaksbehId"/&gt;
 *         &lt;element name="utbetalesTilId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfnrOrgnr" minOccurs="0"/&gt;
 *         &lt;element name="datoUtbetalesTilIdFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="kodeArbeidsgiver" type="{http://www.trygdeetaten.no/skjema/oppdrag}TkodeArbeidsgiver" minOccurs="0"/&gt;
 *         &lt;element name="henvisning" type="{http://www.trygdeetaten.no/skjema/oppdrag}Thenvisning" minOccurs="0"/&gt;
 *         &lt;element name="typeSoknad" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="10"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="refFagsystemId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfagsystemId" minOccurs="0"/&gt;
 *         &lt;element name="refOppdragsId" type="{http://www.trygdeetaten.no/skjema/oppdrag}ToppdragsId" minOccurs="0"/&gt;
 *         &lt;element name="refDelytelseId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TdelytelseId" minOccurs="0"/&gt;
 *         &lt;element name="refLinjeId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TlinjeId" minOccurs="0"/&gt;
 *         &lt;element name="linje-status-151" type="{http://www.trygdeetaten.no/skjema/oppdrag}linje-status-151" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="klassifikasjon-152" type="{http://www.trygdeetaten.no/skjema/oppdrag}klassifikasjon-152" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="skyldner-153" type="{http://www.trygdeetaten.no/skjema/oppdrag}skyldner-153" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="kid-154" type="{http://www.trygdeetaten.no/skjema/oppdrag}kid-154" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="utbetales-til-155" type="{http://www.trygdeetaten.no/skjema/oppdrag}utbetales-til-155" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="refusjonsinfo-156" type="{http://www.trygdeetaten.no/skjema/oppdrag}refusjonsinfo-156" minOccurs="0"/&gt;
 *         &lt;element name="linje-tekst-158" type="{http://www.trygdeetaten.no/skjema/oppdrag}linje-tekst-158" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="linje-enhet-160" type="{http://www.trygdeetaten.no/skjema/oppdrag}linje-enhet-160" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="grad-170" type="{http://www.trygdeetaten.no/skjema/oppdrag}grad-170" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="attestant-180" type="{http://www.trygdeetaten.no/skjema/oppdrag}attestant-180" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="valuta-190" type="{http://www.trygdeetaten.no/skjema/oppdrag}valuta-190" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "oppdrags-linje-150", propOrder = {
    "kodeEndringLinje",
    "kodeStatusLinje",
    "datoStatusFom",
    "vedtakId",
    "delytelseId",
    "linjeId",
    "kodeKlassifik",
    "datoKlassifikFom",
    "datoVedtakFom",
    "datoVedtakTom",
    "sats",
    "fradragTillegg",
    "typeSats",
    "skyldnerId",
    "datoSkyldnerFom",
    "kravhaverId",
    "datoKravhaverFom",
    "kid",
    "datoKidFom",
    "brukKjoreplan",
    "saksbehId",
    "utbetalesTilId",
    "datoUtbetalesTilIdFom",
    "kodeArbeidsgiver",
    "henvisning",
    "typeSoknad",
    "refFagsystemId",
    "refOppdragsId",
    "refDelytelseId",
    "refLinjeId",
    "linjeStatus151",
    "klassifikasjon152",
    "skyldner153",
    "kid154",
    "utbetalesTil155",
    "refusjonsinfo156",
    "linjeTekst158",
    "linjeEnhet160",
    "grad170",
    "attestant180",
    "valuta190"
})
public class OppdragsLinje150 {

    @XmlElement(required = true)
    protected String kodeEndringLinje;
    @XmlSchemaType(name = "string")
    protected TkodeStatusLinje kodeStatusLinje;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoStatusFom;
    protected String vedtakId;
    protected String delytelseId;
    protected BigInteger linjeId;
    @XmlElement(required = true)
    protected String kodeKlassifik;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoKlassifikFom;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoVedtakFom;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoVedtakTom;
    @XmlElement(required = true)
    protected BigDecimal sats;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TfradragTillegg fradragTillegg;
    @XmlElement(required = true)
    protected String typeSats;
    protected String skyldnerId;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoSkyldnerFom;
    protected String kravhaverId;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoKravhaverFom;
    protected String kid;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoKidFom;
    protected String brukKjoreplan;
    @XmlElement(required = true)
    protected String saksbehId;
    protected String utbetalesTilId;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoUtbetalesTilIdFom;
    @XmlSchemaType(name = "string")
    protected TkodeArbeidsgiver kodeArbeidsgiver;
    protected String henvisning;
    protected String typeSoknad;
    protected String refFagsystemId;
    protected Long refOppdragsId;
    protected String refDelytelseId;
    protected BigInteger refLinjeId;
    @XmlElement(name = "linje-status-151")
    protected List<LinjeStatus151> linjeStatus151;
    @XmlElement(name = "klassifikasjon-152")
    protected List<Klassifikasjon152> klassifikasjon152;
    @XmlElement(name = "skyldner-153")
    protected List<Skyldner153> skyldner153;
    @XmlElement(name = "kid-154")
    protected List<Kid154> kid154;
    @XmlElement(name = "utbetales-til-155")
    protected List<UtbetalesTil155> utbetalesTil155;
    @XmlElement(name = "refusjonsinfo-156")
    protected Refusjonsinfo156 refusjonsinfo156;
    @XmlElement(name = "linje-tekst-158")
    protected List<LinjeTekst158> linjeTekst158;
    @XmlElement(name = "linje-enhet-160")
    protected List<LinjeEnhet160> linjeEnhet160;
    @XmlElement(name = "grad-170")
    protected List<no.nav.trygdeetaten.skjema.oppdrag.Grad170> grad170;
    @XmlElement(name = "attestant-180")
    protected List<Attestant180> attestant180;
    @XmlElement(name = "valuta-190")
    protected List<Valuta190> valuta190;

    /**
     * Gets the value of the kodeEndringLinje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeEndringLinje() {
        return kodeEndringLinje;
    }

    /**
     * Sets the value of the kodeEndringLinje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeEndringLinje(String value) {
        this.kodeEndringLinje = value;
    }

    /**
     * Gets the value of the kodeStatusLinje property.
     * 
     * @return
     *     possible object is
     *     {@link TkodeStatusLinje }
     *     
     */
    public TkodeStatusLinje getKodeStatusLinje() {
        return kodeStatusLinje;
    }

    /**
     * Sets the value of the kodeStatusLinje property.
     * 
     * @param value
     *     allowed object is
     *     {@link TkodeStatusLinje }
     *     
     */
    public void setKodeStatusLinje(TkodeStatusLinje value) {
        this.kodeStatusLinje = value;
    }

    /**
     * Gets the value of the datoStatusFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoStatusFom() {
        return datoStatusFom;
    }

    /**
     * Sets the value of the datoStatusFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoStatusFom(XMLGregorianCalendar value) {
        this.datoStatusFom = value;
    }

    /**
     * Gets the value of the vedtakId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVedtakId() {
        return vedtakId;
    }

    /**
     * Sets the value of the vedtakId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVedtakId(String value) {
        this.vedtakId = value;
    }

    /**
     * Gets the value of the delytelseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelytelseId() {
        return delytelseId;
    }

    /**
     * Sets the value of the delytelseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelytelseId(String value) {
        this.delytelseId = value;
    }

    /**
     * Gets the value of the linjeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLinjeId() {
        return linjeId;
    }

    /**
     * Sets the value of the linjeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLinjeId(BigInteger value) {
        this.linjeId = value;
    }

    /**
     * Gets the value of the kodeKlassifik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeKlassifik() {
        return kodeKlassifik;
    }

    /**
     * Sets the value of the kodeKlassifik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeKlassifik(String value) {
        this.kodeKlassifik = value;
    }

    /**
     * Gets the value of the datoKlassifikFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoKlassifikFom() {
        return datoKlassifikFom;
    }

    /**
     * Sets the value of the datoKlassifikFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoKlassifikFom(XMLGregorianCalendar value) {
        this.datoKlassifikFom = value;
    }

    /**
     * Gets the value of the datoVedtakFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoVedtakFom() {
        return datoVedtakFom;
    }

    /**
     * Sets the value of the datoVedtakFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoVedtakFom(XMLGregorianCalendar value) {
        this.datoVedtakFom = value;
    }

    /**
     * Gets the value of the datoVedtakTom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoVedtakTom() {
        return datoVedtakTom;
    }

    /**
     * Sets the value of the datoVedtakTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoVedtakTom(XMLGregorianCalendar value) {
        this.datoVedtakTom = value;
    }

    /**
     * Gets the value of the sats property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSats() {
        return sats;
    }

    /**
     * Sets the value of the sats property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSats(BigDecimal value) {
        this.sats = value;
    }

    /**
     * Gets the value of the fradragTillegg property.
     * 
     * @return
     *     possible object is
     *     {@link TfradragTillegg }
     *     
     */
    public TfradragTillegg getFradragTillegg() {
        return fradragTillegg;
    }

    /**
     * Sets the value of the fradragTillegg property.
     * 
     * @param value
     *     allowed object is
     *     {@link TfradragTillegg }
     *     
     */
    public void setFradragTillegg(TfradragTillegg value) {
        this.fradragTillegg = value;
    }

    /**
     * Gets the value of the typeSats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeSats() {
        return typeSats;
    }

    /**
     * Sets the value of the typeSats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeSats(String value) {
        this.typeSats = value;
    }

    /**
     * Gets the value of the skyldnerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSkyldnerId() {
        return skyldnerId;
    }

    /**
     * Sets the value of the skyldnerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSkyldnerId(String value) {
        this.skyldnerId = value;
    }

    /**
     * Gets the value of the datoSkyldnerFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoSkyldnerFom() {
        return datoSkyldnerFom;
    }

    /**
     * Sets the value of the datoSkyldnerFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoSkyldnerFom(XMLGregorianCalendar value) {
        this.datoSkyldnerFom = value;
    }

    /**
     * Gets the value of the kravhaverId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKravhaverId() {
        return kravhaverId;
    }

    /**
     * Sets the value of the kravhaverId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKravhaverId(String value) {
        this.kravhaverId = value;
    }

    /**
     * Gets the value of the datoKravhaverFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoKravhaverFom() {
        return datoKravhaverFom;
    }

    /**
     * Sets the value of the datoKravhaverFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoKravhaverFom(XMLGregorianCalendar value) {
        this.datoKravhaverFom = value;
    }

    /**
     * Gets the value of the kid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKid() {
        return kid;
    }

    /**
     * Sets the value of the kid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKid(String value) {
        this.kid = value;
    }

    /**
     * Gets the value of the datoKidFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoKidFom() {
        return datoKidFom;
    }

    /**
     * Sets the value of the datoKidFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoKidFom(XMLGregorianCalendar value) {
        this.datoKidFom = value;
    }

    /**
     * Gets the value of the brukKjoreplan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrukKjoreplan() {
        return brukKjoreplan;
    }

    /**
     * Sets the value of the brukKjoreplan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrukKjoreplan(String value) {
        this.brukKjoreplan = value;
    }

    /**
     * Gets the value of the saksbehId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaksbehId() {
        return saksbehId;
    }

    /**
     * Sets the value of the saksbehId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaksbehId(String value) {
        this.saksbehId = value;
    }

    /**
     * Gets the value of the utbetalesTilId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtbetalesTilId() {
        return utbetalesTilId;
    }

    /**
     * Sets the value of the utbetalesTilId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtbetalesTilId(String value) {
        this.utbetalesTilId = value;
    }

    /**
     * Gets the value of the datoUtbetalesTilIdFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoUtbetalesTilIdFom() {
        return datoUtbetalesTilIdFom;
    }

    /**
     * Sets the value of the datoUtbetalesTilIdFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoUtbetalesTilIdFom(XMLGregorianCalendar value) {
        this.datoUtbetalesTilIdFom = value;
    }

    /**
     * Gets the value of the kodeArbeidsgiver property.
     * 
     * @return
     *     possible object is
     *     {@link TkodeArbeidsgiver }
     *     
     */
    public TkodeArbeidsgiver getKodeArbeidsgiver() {
        return kodeArbeidsgiver;
    }

    /**
     * Sets the value of the kodeArbeidsgiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link TkodeArbeidsgiver }
     *     
     */
    public void setKodeArbeidsgiver(TkodeArbeidsgiver value) {
        this.kodeArbeidsgiver = value;
    }

    /**
     * Gets the value of the henvisning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHenvisning() {
        return henvisning;
    }

    /**
     * Sets the value of the henvisning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHenvisning(String value) {
        this.henvisning = value;
    }

    /**
     * Gets the value of the typeSoknad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeSoknad() {
        return typeSoknad;
    }

    /**
     * Sets the value of the typeSoknad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeSoknad(String value) {
        this.typeSoknad = value;
    }

    /**
     * Gets the value of the refFagsystemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefFagsystemId() {
        return refFagsystemId;
    }

    /**
     * Sets the value of the refFagsystemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefFagsystemId(String value) {
        this.refFagsystemId = value;
    }

    /**
     * Gets the value of the refOppdragsId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRefOppdragsId() {
        return refOppdragsId;
    }

    /**
     * Sets the value of the refOppdragsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRefOppdragsId(Long value) {
        this.refOppdragsId = value;
    }

    /**
     * Gets the value of the refDelytelseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefDelytelseId() {
        return refDelytelseId;
    }

    /**
     * Sets the value of the refDelytelseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefDelytelseId(String value) {
        this.refDelytelseId = value;
    }

    /**
     * Gets the value of the refLinjeId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRefLinjeId() {
        return refLinjeId;
    }

    /**
     * Sets the value of the refLinjeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRefLinjeId(BigInteger value) {
        this.refLinjeId = value;
    }

    /**
     * Gets the value of the linjeStatus151 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linjeStatus151 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinjeStatus151().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinjeStatus151 }
     * 
     * 
     */
    public List<LinjeStatus151> getLinjeStatus151() {
        if (linjeStatus151 == null) {
            linjeStatus151 = new ArrayList<LinjeStatus151>();
        }
        return this.linjeStatus151;
    }

    /**
     * Gets the value of the klassifikasjon152 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the klassifikasjon152 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKlassifikasjon152().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Klassifikasjon152 }
     * 
     * 
     */
    public List<Klassifikasjon152> getKlassifikasjon152() {
        if (klassifikasjon152 == null) {
            klassifikasjon152 = new ArrayList<Klassifikasjon152>();
        }
        return this.klassifikasjon152;
    }

    /**
     * Gets the value of the skyldner153 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the skyldner153 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSkyldner153().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Skyldner153 }
     * 
     * 
     */
    public List<Skyldner153> getSkyldner153() {
        if (skyldner153 == null) {
            skyldner153 = new ArrayList<Skyldner153>();
        }
        return this.skyldner153;
    }

    /**
     * Gets the value of the kid154 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kid154 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKid154().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Kid154 }
     * 
     * 
     */
    public List<Kid154> getKid154() {
        if (kid154 == null) {
            kid154 = new ArrayList<Kid154>();
        }
        return this.kid154;
    }

    /**
     * Gets the value of the utbetalesTil155 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the utbetalesTil155 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUtbetalesTil155().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UtbetalesTil155 }
     * 
     * 
     */
    public List<UtbetalesTil155> getUtbetalesTil155() {
        if (utbetalesTil155 == null) {
            utbetalesTil155 = new ArrayList<UtbetalesTil155>();
        }
        return this.utbetalesTil155;
    }

    /**
     * Gets the value of the refusjonsinfo156 property.
     * 
     * @return
     *     possible object is
     *     {@link Refusjonsinfo156 }
     *     
     */
    public Refusjonsinfo156 getRefusjonsinfo156() {
        return refusjonsinfo156;
    }

    /**
     * Sets the value of the refusjonsinfo156 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Refusjonsinfo156 }
     *     
     */
    public void setRefusjonsinfo156(Refusjonsinfo156 value) {
        this.refusjonsinfo156 = value;
    }

    /**
     * Gets the value of the linjeTekst158 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linjeTekst158 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinjeTekst158().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinjeTekst158 }
     * 
     * 
     */
    public List<LinjeTekst158> getLinjeTekst158() {
        if (linjeTekst158 == null) {
            linjeTekst158 = new ArrayList<LinjeTekst158>();
        }
        return this.linjeTekst158;
    }

    /**
     * Gets the value of the linjeEnhet160 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linjeEnhet160 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinjeEnhet160().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinjeEnhet160 }
     * 
     * 
     */
    public List<LinjeEnhet160> getLinjeEnhet160() {
        if (linjeEnhet160 == null) {
            linjeEnhet160 = new ArrayList<LinjeEnhet160>();
        }
        return this.linjeEnhet160;
    }

    /**
     * Gets the value of the grad170 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the grad170 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGrad170().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link no.nav.trygdeetaten.skjema.oppdrag.Grad170 }
     * 
     * 
     */
    public List<no.nav.trygdeetaten.skjema.oppdrag.Grad170> getGrad170() {
        if (grad170 == null) {
            grad170 = new ArrayList<no.nav.trygdeetaten.skjema.oppdrag.Grad170>();
        }
        return this.grad170;
    }

    /**
     * Gets the value of the attestant180 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attestant180 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttestant180().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attestant180 }
     * 
     * 
     */
    public List<Attestant180> getAttestant180() {
        if (attestant180 == null) {
            attestant180 = new ArrayList<Attestant180>();
        }
        return this.attestant180;
    }

    /**
     * Gets the value of the valuta190 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuta190 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuta190().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Valuta190 }
     * 
     * 
     */
    public List<Valuta190> getValuta190() {
        if (valuta190 == null) {
            valuta190 = new ArrayList<Valuta190>();
        }
        return this.valuta190;
    }

    public OppdragsLinje150 withKodeEndringLinje(String value) {
        setKodeEndringLinje(value);
        return this;
    }

    public OppdragsLinje150 withKodeStatusLinje(TkodeStatusLinje value) {
        setKodeStatusLinje(value);
        return this;
    }

    public OppdragsLinje150 withDatoStatusFom(XMLGregorianCalendar value) {
        setDatoStatusFom(value);
        return this;
    }

    public OppdragsLinje150 withVedtakId(String value) {
        setVedtakId(value);
        return this;
    }

    public OppdragsLinje150 withDelytelseId(String value) {
        setDelytelseId(value);
        return this;
    }

    public OppdragsLinje150 withLinjeId(BigInteger value) {
        setLinjeId(value);
        return this;
    }

    public OppdragsLinje150 withKodeKlassifik(String value) {
        setKodeKlassifik(value);
        return this;
    }

    public OppdragsLinje150 withDatoKlassifikFom(XMLGregorianCalendar value) {
        setDatoKlassifikFom(value);
        return this;
    }

    public OppdragsLinje150 withDatoVedtakFom(XMLGregorianCalendar value) {
        setDatoVedtakFom(value);
        return this;
    }

    public OppdragsLinje150 withDatoVedtakTom(XMLGregorianCalendar value) {
        setDatoVedtakTom(value);
        return this;
    }

    public OppdragsLinje150 withSats(BigDecimal value) {
        setSats(value);
        return this;
    }

    public OppdragsLinje150 withFradragTillegg(TfradragTillegg value) {
        setFradragTillegg(value);
        return this;
    }

    public OppdragsLinje150 withTypeSats(String value) {
        setTypeSats(value);
        return this;
    }

    public OppdragsLinje150 withSkyldnerId(String value) {
        setSkyldnerId(value);
        return this;
    }

    public OppdragsLinje150 withDatoSkyldnerFom(XMLGregorianCalendar value) {
        setDatoSkyldnerFom(value);
        return this;
    }

    public OppdragsLinje150 withKravhaverId(String value) {
        setKravhaverId(value);
        return this;
    }

    public OppdragsLinje150 withDatoKravhaverFom(XMLGregorianCalendar value) {
        setDatoKravhaverFom(value);
        return this;
    }

    public OppdragsLinje150 withKid(String value) {
        setKid(value);
        return this;
    }

    public OppdragsLinje150 withDatoKidFom(XMLGregorianCalendar value) {
        setDatoKidFom(value);
        return this;
    }

    public OppdragsLinje150 withBrukKjoreplan(String value) {
        setBrukKjoreplan(value);
        return this;
    }

    public OppdragsLinje150 withSaksbehId(String value) {
        setSaksbehId(value);
        return this;
    }

    public OppdragsLinje150 withUtbetalesTilId(String value) {
        setUtbetalesTilId(value);
        return this;
    }

    public OppdragsLinje150 withDatoUtbetalesTilIdFom(XMLGregorianCalendar value) {
        setDatoUtbetalesTilIdFom(value);
        return this;
    }

    public OppdragsLinje150 withKodeArbeidsgiver(TkodeArbeidsgiver value) {
        setKodeArbeidsgiver(value);
        return this;
    }

    public OppdragsLinje150 withHenvisning(String value) {
        setHenvisning(value);
        return this;
    }

    public OppdragsLinje150 withTypeSoknad(String value) {
        setTypeSoknad(value);
        return this;
    }

    public OppdragsLinje150 withRefFagsystemId(String value) {
        setRefFagsystemId(value);
        return this;
    }

    public OppdragsLinje150 withRefOppdragsId(Long value) {
        setRefOppdragsId(value);
        return this;
    }

    public OppdragsLinje150 withRefDelytelseId(String value) {
        setRefDelytelseId(value);
        return this;
    }

    public OppdragsLinje150 withRefLinjeId(BigInteger value) {
        setRefLinjeId(value);
        return this;
    }

    public OppdragsLinje150 withLinjeStatus151(LinjeStatus151 ... values) {
        if (values!= null) {
            for (LinjeStatus151 value: values) {
                getLinjeStatus151().add(value);
            }
        }
        return this;
    }

    public OppdragsLinje150 withLinjeStatus151(Collection<LinjeStatus151> values) {
        if (values!= null) {
            getLinjeStatus151().addAll(values);
        }
        return this;
    }

    public OppdragsLinje150 withKlassifikasjon152(Klassifikasjon152 ... values) {
        if (values!= null) {
            for (Klassifikasjon152 value: values) {
                getKlassifikasjon152().add(value);
            }
        }
        return this;
    }

    public OppdragsLinje150 withKlassifikasjon152(Collection<Klassifikasjon152> values) {
        if (values!= null) {
            getKlassifikasjon152().addAll(values);
        }
        return this;
    }

    public OppdragsLinje150 withSkyldner153(Skyldner153 ... values) {
        if (values!= null) {
            for (Skyldner153 value: values) {
                getSkyldner153().add(value);
            }
        }
        return this;
    }

    public OppdragsLinje150 withSkyldner153(Collection<Skyldner153> values) {
        if (values!= null) {
            getSkyldner153().addAll(values);
        }
        return this;
    }

    public OppdragsLinje150 withKid154(Kid154 ... values) {
        if (values!= null) {
            for (Kid154 value: values) {
                getKid154().add(value);
            }
        }
        return this;
    }

    public OppdragsLinje150 withKid154(Collection<Kid154> values) {
        if (values!= null) {
            getKid154().addAll(values);
        }
        return this;
    }

    public OppdragsLinje150 withUtbetalesTil155(UtbetalesTil155 ... values) {
        if (values!= null) {
            for (UtbetalesTil155 value: values) {
                getUtbetalesTil155().add(value);
            }
        }
        return this;
    }

    public OppdragsLinje150 withUtbetalesTil155(Collection<UtbetalesTil155> values) {
        if (values!= null) {
            getUtbetalesTil155().addAll(values);
        }
        return this;
    }

    public OppdragsLinje150 withRefusjonsinfo156(Refusjonsinfo156 value) {
        setRefusjonsinfo156(value);
        return this;
    }

    public OppdragsLinje150 withLinjeTekst158(LinjeTekst158 ... values) {
        if (values!= null) {
            for (LinjeTekst158 value: values) {
                getLinjeTekst158().add(value);
            }
        }
        return this;
    }

    public OppdragsLinje150 withLinjeTekst158(Collection<LinjeTekst158> values) {
        if (values!= null) {
            getLinjeTekst158().addAll(values);
        }
        return this;
    }

    public OppdragsLinje150 withLinjeEnhet160(LinjeEnhet160 ... values) {
        if (values!= null) {
            for (LinjeEnhet160 value: values) {
                getLinjeEnhet160().add(value);
            }
        }
        return this;
    }

    public OppdragsLinje150 withLinjeEnhet160(Collection<LinjeEnhet160> values) {
        if (values!= null) {
            getLinjeEnhet160().addAll(values);
        }
        return this;
    }

    public OppdragsLinje150 withGrad170(no.nav.trygdeetaten.skjema.oppdrag.Grad170... values) {
        if (values!= null) {
            for (no.nav.trygdeetaten.skjema.oppdrag.Grad170 value: values) {
                getGrad170().add(value);
            }
        }
        return this;
    }

    public OppdragsLinje150 withGrad170(Collection<Grad170> values) {
        if (values!= null) {
            getGrad170().addAll(values);
        }
        return this;
    }

    public OppdragsLinje150 withAttestant180(Attestant180 ... values) {
        if (values!= null) {
            for (Attestant180 value: values) {
                getAttestant180().add(value);
            }
        }
        return this;
    }

    public OppdragsLinje150 withAttestant180(Collection<Attestant180> values) {
        if (values!= null) {
            getAttestant180().addAll(values);
        }
        return this;
    }

    public OppdragsLinje150 withValuta190(Valuta190 ... values) {
        if (values!= null) {
            for (Valuta190 value: values) {
                getValuta190().add(value);
            }
        }
        return this;
    }

    public OppdragsLinje150 withValuta190(Collection<Valuta190> values) {
        if (values!= null) {
            getValuta190().addAll(values);
        }
        return this;
    }

}
