//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import jakarta.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Inneholder elementene som skal være med i en input 300-rekord, Simulering
 *             
 * 
 * <p>Java class for simulerings-periode-300 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simulerings-periode-300"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="datoSimulerFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *         &lt;element name="datoSimulerTom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simulerings-periode-300", propOrder = {
    "datoSimulerFom",
    "datoSimulerTom"
})
public class SimuleringsPeriode300 {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoSimulerFom;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoSimulerTom;

    /**
     * Gets the value of the datoSimulerFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoSimulerFom() {
        return datoSimulerFom;
    }

    /**
     * Sets the value of the datoSimulerFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoSimulerFom(XMLGregorianCalendar value) {
        this.datoSimulerFom = value;
    }

    /**
     * Gets the value of the datoSimulerTom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoSimulerTom() {
        return datoSimulerTom;
    }

    /**
     * Sets the value of the datoSimulerTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoSimulerTom(XMLGregorianCalendar value) {
        this.datoSimulerTom = value;
    }

    public SimuleringsPeriode300 withDatoSimulerFom(XMLGregorianCalendar value) {
        setDatoSimulerFom(value);
        return this;
    }

    public SimuleringsPeriode300 withDatoSimulerTom(XMLGregorianCalendar value) {
        setDatoSimulerTom(value);
        return this;
    }

}
