//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.*;


/**
 * Inneholder alle output 301-rekord linjene, Simulering
 * 
 * <p>Java class for simulerings-resultat-301 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simulerings-resultat-301"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="simulerings-resultat-linje-301" type="{http://www.trygdeetaten.no/skjema/oppdrag}simulerings-resultat-linje-301" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="simuleringsResultat" type="{http://www.trygdeetaten.no/skjema/oppdrag}simuleringsResultat" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simulerings-resultat-301", propOrder = {
    "simuleringsResultatLinje301",
    "simuleringsResultat"
})
public class SimuleringsResultat301 {

    @XmlElement(name = "simulerings-resultat-linje-301")
    protected List<SimuleringsResultatLinje301> simuleringsResultatLinje301;
    protected List<SimuleringsResultat> simuleringsResultat;

    /**
     * Gets the value of the simuleringsResultatLinje301 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simuleringsResultatLinje301 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimuleringsResultatLinje301().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimuleringsResultatLinje301 }
     * 
     * 
     */
    public List<SimuleringsResultatLinje301> getSimuleringsResultatLinje301() {
        if (simuleringsResultatLinje301 == null) {
            simuleringsResultatLinje301 = new ArrayList<SimuleringsResultatLinje301>();
        }
        return this.simuleringsResultatLinje301;
    }

    /**
     * Gets the value of the simuleringsResultat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simuleringsResultat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimuleringsResultat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimuleringsResultat }
     * 
     * 
     */
    public List<SimuleringsResultat> getSimuleringsResultat() {
        if (simuleringsResultat == null) {
            simuleringsResultat = new ArrayList<SimuleringsResultat>();
        }
        return this.simuleringsResultat;
    }

    public SimuleringsResultat301 withSimuleringsResultatLinje301(SimuleringsResultatLinje301 ... values) {
        if (values!= null) {
            for (SimuleringsResultatLinje301 value: values) {
                getSimuleringsResultatLinje301().add(value);
            }
        }
        return this;
    }

    public SimuleringsResultat301 withSimuleringsResultatLinje301(Collection<SimuleringsResultatLinje301> values) {
        if (values!= null) {
            getSimuleringsResultatLinje301().addAll(values);
        }
        return this;
    }

    public SimuleringsResultat301 withSimuleringsResultat(SimuleringsResultat... values) {
        if (values!= null) {
            for (SimuleringsResultat value: values) {
                getSimuleringsResultat().add(value);
            }
        }
        return this;
    }

    public SimuleringsResultat301 withSimuleringsResultat(Collection<SimuleringsResultat> values) {
        if (values!= null) {
            getSimuleringsResultat().addAll(values);
        }
        return this;
    }

}
