//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.*;


/**
 * Inneholder elementene som skal være med i en input 170-rekord, Grad
 * 
 * <p>Java class for grad-170 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="grad-170"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="typeGrad"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="4"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="grad" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tgrad"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grad-170", propOrder = {
    "typeGrad",
    "grad"
})
public class Grad170 {

    @XmlElement(required = true)
    protected String typeGrad;
    @XmlElement(required = true)
    protected BigInteger grad;

    /**
     * Gets the value of the typeGrad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeGrad() {
        return typeGrad;
    }

    /**
     * Sets the value of the typeGrad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeGrad(String value) {
        this.typeGrad = value;
    }

    /**
     * Gets the value of the grad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGrad() {
        return grad;
    }

    /**
     * Sets the value of the grad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGrad(BigInteger value) {
        this.grad = value;
    }

    public Grad170 withTypeGrad(String value) {
        setTypeGrad(value);
        return this;
    }

    public Grad170 withGrad(BigInteger value) {
        setGrad(value);
        return this;
    }

}
