//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import java.math.BigDecimal;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Inneholder elementene som skal være med i en output 301-rekord, Simulering
 *             
 * 
 * <p>Java class for simulerings-resultat-linje-301 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simulerings-resultat-linje-301"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="fagsystemId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfagsystemId"/&gt;
 *         &lt;element name="oppdragGjelderId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfnrOrgnr"/&gt;
 *         &lt;element name="bostedsEnhet" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tenhet"/&gt;
 *         &lt;element name="utbetFrekvens" type="{http://www.trygdeetaten.no/skjema/oppdrag}TutbetFrekvens"/&gt;
 *         &lt;element name="vedtakId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TvedtakId"/&gt;
 *         &lt;element name="delytelseId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TdelytelseId"/&gt;
 *         &lt;element name="utbetalesTilId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfnrOrgnr"/&gt;
 *         &lt;element name="gironr" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="11"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="behandlEnhet" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tenhet"/&gt;
 *         &lt;element name="datoKjores" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato"/&gt;
 *         &lt;element name="datoBeregnFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato"/&gt;
 *         &lt;element name="datoBeregnTom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato"/&gt;
 *         &lt;element name="kontostreng"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="7"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="kodeBeh"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="1"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="kontotekst"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="30"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="belop" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tbelop"/&gt;
 *         &lt;element name="fradragTillegg" type="{http://www.trygdeetaten.no/skjema/oppdrag}TfradragTillegg"/&gt;
 *         &lt;element name="grad" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tgrad" minOccurs="0"/&gt;
 *         &lt;element name="saksbehId" type="{http://www.trygdeetaten.no/skjema/oppdrag}TsaksbehId"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simulerings-resultat-linje-301", propOrder = {
    "fagsystemId",
    "oppdragGjelderId",
    "bostedsEnhet",
    "utbetFrekvens",
    "vedtakId",
    "delytelseId",
    "utbetalesTilId",
    "gironr",
    "behandlEnhet",
    "datoKjores",
    "datoBeregnFom",
    "datoBeregnTom",
    "kontostreng",
    "kodeBeh",
    "kontotekst",
    "belop",
    "fradragTillegg",
    "grad",
    "saksbehId"
})
public class SimuleringsResultatLinje301 {

    @XmlElement(required = true)
    protected String fagsystemId;
    @XmlElement(required = true)
    protected String oppdragGjelderId;
    @XmlElement(required = true)
    protected String bostedsEnhet;
    @XmlElement(required = true)
    protected String utbetFrekvens;
    @XmlElement(required = true)
    protected String vedtakId;
    @XmlElement(required = true)
    protected String delytelseId;
    @XmlElement(required = true)
    protected String utbetalesTilId;
    protected String gironr;
    @XmlElement(required = true)
    protected String behandlEnhet;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoKjores;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoBeregnFom;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datoBeregnTom;
    @XmlElement(required = true)
    protected String kontostreng;
    @XmlElement(required = true)
    protected String kodeBeh;
    @XmlElement(required = true)
    protected String kontotekst;
    @XmlElement(required = true)
    protected BigDecimal belop;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected TfradragTillegg fradragTillegg;
    protected BigInteger grad;
    @XmlElement(required = true)
    protected String saksbehId;

    /**
     * Gets the value of the fagsystemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFagsystemId() {
        return fagsystemId;
    }

    /**
     * Sets the value of the fagsystemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFagsystemId(String value) {
        this.fagsystemId = value;
    }

    /**
     * Gets the value of the oppdragGjelderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOppdragGjelderId() {
        return oppdragGjelderId;
    }

    /**
     * Sets the value of the oppdragGjelderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOppdragGjelderId(String value) {
        this.oppdragGjelderId = value;
    }

    /**
     * Gets the value of the bostedsEnhet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBostedsEnhet() {
        return bostedsEnhet;
    }

    /**
     * Sets the value of the bostedsEnhet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBostedsEnhet(String value) {
        this.bostedsEnhet = value;
    }

    /**
     * Gets the value of the utbetFrekvens property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtbetFrekvens() {
        return utbetFrekvens;
    }

    /**
     * Sets the value of the utbetFrekvens property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtbetFrekvens(String value) {
        this.utbetFrekvens = value;
    }

    /**
     * Gets the value of the vedtakId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVedtakId() {
        return vedtakId;
    }

    /**
     * Sets the value of the vedtakId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVedtakId(String value) {
        this.vedtakId = value;
    }

    /**
     * Gets the value of the delytelseId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelytelseId() {
        return delytelseId;
    }

    /**
     * Sets the value of the delytelseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelytelseId(String value) {
        this.delytelseId = value;
    }

    /**
     * Gets the value of the utbetalesTilId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUtbetalesTilId() {
        return utbetalesTilId;
    }

    /**
     * Sets the value of the utbetalesTilId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUtbetalesTilId(String value) {
        this.utbetalesTilId = value;
    }

    /**
     * Gets the value of the gironr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGironr() {
        return gironr;
    }

    /**
     * Sets the value of the gironr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGironr(String value) {
        this.gironr = value;
    }

    /**
     * Gets the value of the behandlEnhet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBehandlEnhet() {
        return behandlEnhet;
    }

    /**
     * Sets the value of the behandlEnhet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBehandlEnhet(String value) {
        this.behandlEnhet = value;
    }

    /**
     * Gets the value of the datoKjores property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoKjores() {
        return datoKjores;
    }

    /**
     * Sets the value of the datoKjores property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoKjores(XMLGregorianCalendar value) {
        this.datoKjores = value;
    }

    /**
     * Gets the value of the datoBeregnFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoBeregnFom() {
        return datoBeregnFom;
    }

    /**
     * Sets the value of the datoBeregnFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoBeregnFom(XMLGregorianCalendar value) {
        this.datoBeregnFom = value;
    }

    /**
     * Gets the value of the datoBeregnTom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatoBeregnTom() {
        return datoBeregnTom;
    }

    /**
     * Sets the value of the datoBeregnTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatoBeregnTom(XMLGregorianCalendar value) {
        this.datoBeregnTom = value;
    }

    /**
     * Gets the value of the kontostreng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKontostreng() {
        return kontostreng;
    }

    /**
     * Sets the value of the kontostreng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKontostreng(String value) {
        this.kontostreng = value;
    }

    /**
     * Gets the value of the kodeBeh property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodeBeh() {
        return kodeBeh;
    }

    /**
     * Sets the value of the kodeBeh property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodeBeh(String value) {
        this.kodeBeh = value;
    }

    /**
     * Gets the value of the kontotekst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKontotekst() {
        return kontotekst;
    }

    /**
     * Sets the value of the kontotekst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKontotekst(String value) {
        this.kontotekst = value;
    }

    /**
     * Gets the value of the belop property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBelop() {
        return belop;
    }

    /**
     * Sets the value of the belop property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBelop(BigDecimal value) {
        this.belop = value;
    }

    /**
     * Gets the value of the fradragTillegg property.
     * 
     * @return
     *     possible object is
     *     {@link TfradragTillegg }
     *     
     */
    public TfradragTillegg getFradragTillegg() {
        return fradragTillegg;
    }

    /**
     * Sets the value of the fradragTillegg property.
     * 
     * @param value
     *     allowed object is
     *     {@link TfradragTillegg }
     *     
     */
    public void setFradragTillegg(TfradragTillegg value) {
        this.fradragTillegg = value;
    }

    /**
     * Gets the value of the grad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGrad() {
        return grad;
    }

    /**
     * Sets the value of the grad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGrad(BigInteger value) {
        this.grad = value;
    }

    /**
     * Gets the value of the saksbehId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaksbehId() {
        return saksbehId;
    }

    /**
     * Sets the value of the saksbehId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaksbehId(String value) {
        this.saksbehId = value;
    }

    public SimuleringsResultatLinje301 withFagsystemId(String value) {
        setFagsystemId(value);
        return this;
    }

    public SimuleringsResultatLinje301 withOppdragGjelderId(String value) {
        setOppdragGjelderId(value);
        return this;
    }

    public SimuleringsResultatLinje301 withBostedsEnhet(String value) {
        setBostedsEnhet(value);
        return this;
    }

    public SimuleringsResultatLinje301 withUtbetFrekvens(String value) {
        setUtbetFrekvens(value);
        return this;
    }

    public SimuleringsResultatLinje301 withVedtakId(String value) {
        setVedtakId(value);
        return this;
    }

    public SimuleringsResultatLinje301 withDelytelseId(String value) {
        setDelytelseId(value);
        return this;
    }

    public SimuleringsResultatLinje301 withUtbetalesTilId(String value) {
        setUtbetalesTilId(value);
        return this;
    }

    public SimuleringsResultatLinje301 withGironr(String value) {
        setGironr(value);
        return this;
    }

    public SimuleringsResultatLinje301 withBehandlEnhet(String value) {
        setBehandlEnhet(value);
        return this;
    }

    public SimuleringsResultatLinje301 withDatoKjores(XMLGregorianCalendar value) {
        setDatoKjores(value);
        return this;
    }

    public SimuleringsResultatLinje301 withDatoBeregnFom(XMLGregorianCalendar value) {
        setDatoBeregnFom(value);
        return this;
    }

    public SimuleringsResultatLinje301 withDatoBeregnTom(XMLGregorianCalendar value) {
        setDatoBeregnTom(value);
        return this;
    }

    public SimuleringsResultatLinje301 withKontostreng(String value) {
        setKontostreng(value);
        return this;
    }

    public SimuleringsResultatLinje301 withKodeBeh(String value) {
        setKodeBeh(value);
        return this;
    }

    public SimuleringsResultatLinje301 withKontotekst(String value) {
        setKontotekst(value);
        return this;
    }

    public SimuleringsResultatLinje301 withBelop(BigDecimal value) {
        setBelop(value);
        return this;
    }

    public SimuleringsResultatLinje301 withFradragTillegg(TfradragTillegg value) {
        setFradragTillegg(value);
        return this;
    }

    public SimuleringsResultatLinje301 withGrad(BigInteger value) {
        setGrad(value);
        return this;
    }

    public SimuleringsResultatLinje301 withSaksbehId(String value) {
        setSaksbehId(value);
        return this;
    }

}
