//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.26 at 08:29:59 AM UTC 
//


package no.nav.trygdeetaten.skjema.oppdrag;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Simulering, Output 312-rekord
 * 
 * <p>Java class for simuleringsPerioder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simuleringsPerioder"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="periodeFom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato"/&gt;
 *         &lt;element name="periodeTom" type="{http://www.trygdeetaten.no/skjema/oppdrag}Tdato"/&gt;
 *         &lt;element name="simuleringsStoppNivaa" type="{http://www.trygdeetaten.no/skjema/oppdrag}simuleringsStoppNivaa" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simuleringsPerioder", propOrder = {
    "periodeFom",
    "periodeTom",
    "simuleringsStoppNivaa"
})
public class SimuleringsPerioder {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar periodeFom;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar periodeTom;
    @XmlElement(required = true)
    protected List<SimuleringsStoppNivaa> simuleringsStoppNivaa;

    /**
     * Gets the value of the periodeFom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodeFom() {
        return periodeFom;
    }

    /**
     * Sets the value of the periodeFom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodeFom(XMLGregorianCalendar value) {
        this.periodeFom = value;
    }

    /**
     * Gets the value of the periodeTom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodeTom() {
        return periodeTom;
    }

    /**
     * Sets the value of the periodeTom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodeTom(XMLGregorianCalendar value) {
        this.periodeTom = value;
    }

    /**
     * Gets the value of the simuleringsStoppNivaa property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simuleringsStoppNivaa property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimuleringsStoppNivaa().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimuleringsStoppNivaa }
     * 
     * 
     */
    public List<SimuleringsStoppNivaa> getSimuleringsStoppNivaa() {
        if (simuleringsStoppNivaa == null) {
            simuleringsStoppNivaa = new ArrayList<SimuleringsStoppNivaa>();
        }
        return this.simuleringsStoppNivaa;
    }

    public SimuleringsPerioder withPeriodeFom(XMLGregorianCalendar value) {
        setPeriodeFom(value);
        return this;
    }

    public SimuleringsPerioder withPeriodeTom(XMLGregorianCalendar value) {
        setPeriodeTom(value);
        return this;
    }

    public SimuleringsPerioder withSimuleringsStoppNivaa(SimuleringsStoppNivaa... values) {
        if (values!= null) {
            for (SimuleringsStoppNivaa value: values) {
                getSimuleringsStoppNivaa().add(value);
            }
        }
        return this;
    }

    public SimuleringsPerioder withSimuleringsStoppNivaa(Collection<SimuleringsStoppNivaa> values) {
        if (values!= null) {
            getSimuleringsStoppNivaa().addAll(values);
        }
        return this;
    }

}
