CREATE TABLE OPPDRAGSTATE
(
    ID BIGSERIAL,
    SOKNAD_ID  UUID NOT NULL,
    CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
    MODIFIED TIMESTAMP NOT NULL DEFAULT NOW(),
    VEDTAK TEXT NOT NULL,
    STATUS VARCHAR(16) NOT NULL,
    OPPDRAGRESPONSE TEXT,
    SIMULERINGRESULT TEXT,
    PRIMARY KEY (ID),
    UNIQUE (SOKNAD_ID)
);

CREATE INDEX OPPDRAGSTATE_MODIFIED_IDX ON OPPDRAGSTATE(MODIFIED);
CREATE INDEX OPPDRAGSTATE_STATUS_IDX ON OPPDRAGSTATE(STATUS);
