name: Spenn-mq branches

on:
  push:
    paths:
      - 'spenn-mq/**'
      - '.github/workflows/spenn-mq-branches.yml'
    branches-ignore:
      - main

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: test and build
        run: ./gradlew :spenn-mq:test :spenn-mq:build
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          image_suffix: mq-branch
          dockerfile: Dockerfile
          docker_context: spenn-mq
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
